### ISSUE TITLE
The 24 hour clock

### ISSUE THREAD

**Issue by OccasionallyCrepuscular** [geronimo66/Pacig-Clock#2]
Hi, I'm wondering if there is somewhere I can see the data & zones collected as a chart for months since use ,rather than them disappearing at midnight.
Can the 24h clock be changed to a shorter or longer duration for those with a Non 24 hour circadian rhythm? (with an ability to re-calibrate as needed) Circadian rhythm disorders are often co-morbid with CFS so it would be a helpful feature 

Any chance that separate alarm patterns can be set for the lilac vs the red zone? (higher tiers would have a different buzzing pattern instead of the amount of seconds between them) 
During times of stress I'm having to change the alarms for basic living activities,to stop it buzzing when lying down,eating etc... so it would be really helpful.

An ability to ease oneself into pacing,so setting it at maybe 102,then 101,the 100 to gradually adjust as one gets more disability aids and learns discipline to stop,instead of being overwhelmed by the alarm going off all the time,I don't know if the age setting would help with that.. 

Appreciate the app,it's been very insightful & you've obviously put a lot of thought into it.

**Comment by geronimo66** [comment]
Thank you for your feedback. 1: Introducing long-term data is challenging due to Fitbit watch limitations and my resources as an independent developer, but I'm keeping the idea in mind. 2: Adjusting for non-24-hour rhythms would complicate the operation; the app should remain simple to use. 3: Different vibration patterns were hard to distinguish in tests, so I now use a simpler system with tiered repetitions. 4: Gradually adjusting heart rate zones isn't effective given the accuracy of pulse measurement and the app's purpose as a rough guideline. I warmly invite interested developers to review the code and suggest enhancements.
