### ISSUE TITLE
Pacig-Clock not available?

### ISSUE THREAD

**Issue by GenevieveAppenzeller** [geronimo66/Pacig-Clock#4]
I‘ve bought a Fitbit Sense 2 Clock only for use for your Pacing App for Post Covid Heart rate monitoring. But it says now the app is not available for my watch. What can I do? I am totally shocked! Please help! Thank you

**Comment by geronimo66** [comment]
Same for me. I was shocked too. I also had to return it due to the same issue. Unfortunately, Fitbit has not provided an SDK for the latest models, Sense 2 and Versa 4, for over two years. Therefore, it is currently impossible to develop apps on these devices. You will have to send it back and get a Versa 3 or the original Sense instead.
